language: ruby
rvm:
  - 1.9.3
  - 1.9.2
  - jruby-18mode
  - jruby-19mode
  - ruby-head
  - jruby-head
  - 1.8.7
  - ree
gemfile:
  - Gemfile
  - bundles/puppet_3_0.gemfile
  - bundles/puppet_2_7.gemfile
